import './styles/_globals.scss'
import { Player } from '@/components/MusicPlayer'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { WidgetProvider } from '@/contexts/LibraryWidgetContext'
import { NavigationProvider } from '@/contexts/NavigationContext'
import { ChildrenProp } from '@/types/Children'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: ChildrenProp) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavigationProvider>
          <WidgetProvider>
            {children}
            <Player.Root>
              <Player.Title />
              <Player.Controls />
              <Player.SoundControl />
            </Player.Root>
          </WidgetProvider>
        </NavigationProvider>
      </body>
    </html>
  )
}
