import { Player } from '@/components/MusicPlayer'
import './styles/_globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { WidgetProvider } from '@/contexts/LibraryWidgetContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WidgetProvider>
          {children}
          <Player.Root>
            <Player.Title />
            <Player.Controls />
            <Player.SoundControl />
          </Player.Root>
        </WidgetProvider>
      </body>
    </html>
  )
}
